# https://gethomepage.dev/widgets/
- glances:
    label: pi5
    url: http://192.168.0.5:61208
    version: 4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk:
      - /
      - /mnt/HDD1

- glances:
    label: pi3
    url: http://192.168.0.3:61208
    version: 4
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    disk: /
