services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.2.0
    container_name: homepage
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - /home/aldo/dev/06-apps-neo-brutalist-home/config:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.0.5,127.0.0.1,localhost,aldof.duckdns.org,aldo-f.duckdns.org,lotte1.duckdns.org,usful.duckdns.org,torrent.aldof.duckdns.org,urbanfix.aldof.duckdns.org,rag.aldof.duckdns.org,jellyfin.aldof.duckdns.org,opencode.dev.aldof.duckdns.org,dev.aldof.duckdns.org,urbanfix.dev.aldof.duckdns.org,stantonius.usful.duckdns.org,stantonius.aldof.duckdns.org
    ports:
      - "4002:3000"
    labels:
      - "traefik.enable=false"
      - "sablier.enable=true"
      - "sablier.group=homepage"
      - "sablier.strategy=blocking"
      - "sablier.session.duration=30m"
      - "sablier.session.inactivity=5m"
      - "sablier.session.inactivity=5m"

networks:
  traefik_net:
    external: true
