services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - /home/aldo/dev/06-apps-neo-brutalist-home/config:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=aldof.duckdns.org
    ports:
      - "4001:3000"
    labels:
      - "traefik.enable=false"
      - "sablier.enable=true"
      - "sablier.group=homepage"
      - "sablier.strategy=blocking"
      - "sablier.session.duration=30m"
      - "sablier.session.inactivity=5m"
      - "sablier.session.inactivity=5m"

networks:
  traefik_net:
    external: true