---
- name: reload traefik
  command: docker restart traefik
  changed_when: true
  become: true

- name: restart metrics timer
  systemd:
    name: 06-apps-neo-brutalist-home-metrics.timer
    state: restarted

- name: restart homepage server
  systemd:
    name: 06-apps-neo-brutalist-home-server
    state: restarted
