networks:
  traefik_net:
    external: true
services:
  jellyfin:
    environment:
    - LISTEN="0.0.0.0:8096"
    - UPSTREAM="jellyfin:8096"
    - SABLIER_API="http://sablier:10000"
    - GROUP="jellyfin"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
