- name: Reload systemd
  command: systemctl daemon-reload
  args:
    chdir: /
  become: true
  async: 30
  poll: 0

- name: Reload sudoers
  command: sudo chmod 0440 {{ sudoers_file }}
  args:
    chdir: /
  become: true
  async: 30
  poll: 0