networks:
  traefik_net:
    external: true
services:
  homepage:
    environment:
    - LISTEN="0.0.0.0:8083"
    - UPSTREAM="homepage:3000"
    - SABLIER_API="http://sablier:10000"
    - GROUP="homepage"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
