networks:
  traefik_net:
    external: true
services:
  torrent:
    environment:
    - LISTEN="0.0.0.0:8091"
    - UPSTREAM="qbittorrent:8080"
    - SABLIER_API="http://sablier:10000"
    - GROUP="torrent"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.torrent.rule=Host(`torrent.aldof.duckdns.org`)
      - traefik.http.routers.torrent.entrypoints=websecure
      - traefik.http.routers.torrent.tls=true
      - traefik.http.routers.torrent.service=torrent
      - traefik.http.services.torrent.loadbalancer.server.port=8091
    ports:
      - "8091:8091"
