networks:
  traefik_net:
    external: true
services:
  homepage:
    environment:
    - LISTEN=0.0.0.0:8083
    - UPSTREAM=homepage:3000
    - SABLIER_API=http://sablier:10000
    - GROUP=homepage
    - SESSION_DURATION=30m
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`aldof.duckdns.org`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=8083