site_name: My Docs
site_url: https://mydomain.github.io
repo_url: https://github.com/me/my-docs-repo
repo_name: me/my-docs-repo
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - navigation.indexes
    - toc.integrate
    - navigation.sections
    - toc.follow
plugins:
  - search
  - multirepo:
      nav_repos:
        - name: thuis
          url: https://github.com/Aldo-f/thuis
        - name: infra
          url: https://github.com/Aldo-f/01-core-infra
nav:
  - Home: docs/index.md
  - Thuis: !import [thuis]
  - Core Infra: !import [infra]
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Aldo-f
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/aldo-fieuw
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@aldo_fieuw
markdown_extensions:
  - toc:
      permalink: true