apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-usful
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`usful.duckdns.org`)
    kind: Rule
    services:
    - name: homepage
      port: 4002