apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: torrent-qbittorrent
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`torrent.aldof.duckdns.org`) || Host(`qbittorrent.aldof.duckdns.org`)
    kind: Rule
    services:
    - name: qbittorrent
      port: 8080
  tls:
    certResolver: duckdns-resolver
