apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: urbanfix
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`urbanfix.aldof.duckdns.org`)
    kind: Rule
    services:
    - name: urbanfix
      port: 8080
  tls:
    secretName: urbanfix-tls-secret