apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: urbanfix
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`urbanfix.aldof.duckdns.org`)
    services:
    - name: urbanfix
      port: 3000
  tls:
    certResolver: duckdns-resolver