apiVersion: v1
kind: Secret
metadata:
  name: freellm-tls-secret
  namespace: default
type: kubernetes.io/tls
# TODO: Copy TLS cert from Docker Traefik letsencrypt volume
# docker exec traefik cat /letsencrypt/acme.json | jq '.[] | select(.Domains.main == "freellm.aldof.duckdns.org")'
data: {}
# Replace with base64 encoded tls.crt and tls.key
# tls.crt: LS0t...
# tls.key: LS0t...