services:
  qdrant:
    image: qdrant/qdrant@sha256:057ee3a8da769fe7310dd3537b4dc7583bf87a95ce8ac43c0af5a46bc580d1fc
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/data
    environment:
      - QDRANT__ALLOW_EMPTY_PAGE_SIZE=true
      - MALLOC_CONF=retain:false
    restart: unless-stopped
    networks:
      - traefik_net

networks:
  traefik_net:
    external: true

volumes:
  qdrant-data:
