networks:
  traefik_net:
    external: true
services:
  hermes-tq:
    environment:
    - LISTEN="0.0.0.0:8088"
    - UPSTREAM="hermes-tq:8788"
    - SABLIER_API="http://sablier:10000"
    - GROUP="hermes-tq"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
