http:
  routers:
    freellm-http:
      rule: "Host(`freellm.aldof.duckdns.org`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: freellmapi

    freellm:
      rule: "Host(`freellm.aldof.duckdns.org`)"
      entryPoints:
        - websecure
      service: freellmapi
      tls:
        certResolver: myresolver

    nextcloud:
      rule: "Host(`cloud.aldof.duckdns.org`)"
      entryPoints:
        - websecure
      service: nextcloud
      tls:
        certResolver: myresolver

    nextcloud-http:
      rule: "Host(`cloud.aldof.duckdns.org`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: nextcloud

    hermes-http:
      rule: "Host(`web.hermes.dev.aldof.duckdns.org`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: hermes-webui

    hermes:
      rule: "Host(`web.hermes.dev.aldof.duckdns.org`)"
      entryPoints:
        - websecure
      service: hermes-webui
      tls:
        certResolver: myresolver

  services:
    freellmapi:
      loadBalancer:
        servers:
          - url: "http://freellmapi:3001"
    
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud:80"

    hermes-webui:
      loadBalancer:
        servers:
          - url: "http://192.168.0.5:8787"

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
