networks:
  traefik_net:
    external: true
services:
  qbittorrent:
    environment:
    - LISTEN="0.0.0.0:8080"
    - UPSTREAM="qbittorrent:8080"
    - SABLIER_API="http://sablier:10000"
    - GROUP="qbittorrent"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
