networks:
  traefik_net:
    external: true
services:
  letspeppol:
    environment:
    - LISTEN="0.0.0.0:8087"
    - UPSTREAM="local-ui-1:80"
    - SABLIER_API="http://sablier:10000"
    - GROUP="letspeppol"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
