networks:
  traefik_net:
    external: true
services:
  nextcloud:
    environment:
    - LISTEN="0.0.0.0:8081"
    - UPSTREAM="nextcloud:80"
    - SABLIER_API="http://sablier:10000"
    - GROUP="nextcloud"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
