networks:
  traefik_net:
    external: true
services:
  vaultwarden:
    environment:
    - LISTEN="0.0.0.0:8084"
    - UPSTREAM="vaultwarden:80"
    - SABLIER_API="http://sablier:10000"
    - GROUP="vaultwarden"
    - SESSION_DURATION="30m"
    image: ghcr.io/vbrandl/sablier-proxy:latest
    networks:
    - traefik_net
    restart: unless-stopped
